---
swagger: '2.0'
info:
  version: 0.0.0
  title: Simple API
paths:
  /hello:
    get:
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Hello'
definitions:
  Hello:
    type: object
    properties:
      code:
        type: integer
        format: int64
      type:
        type: string
      message:
        type: string
    example:
      code: 111
      type: tyaA
      message: this is a test A V
